# Generated by Django 3.1.4 on 2020-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
