# Generated by Django 3.1.4 on 2020-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_auto_20201214_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
