# Generated by Django 3.1.4 on 2020-12-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_auto_20201214_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiries',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='enquiries',
            old_name='message',
            new_name='content',
        ),
    ]
